<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">zend-expressive</span></h1>
    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/zend-expressive-skeleton" target="_blank">zend-expressive skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
    </p>
    <p>
        Expressive builds on zend-stratigility to provide a minimalist PSR-7 middleware framework for PHP.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://zend-expressive.readthedocs.org/en/latest/features/" target="_blank">
                <i class="fa fa-refresh"></i> Agile &amp; Lean
            </a>
        </h2>
        <p>
            Expressive is fast, small and perfect for rapid application development, prototyping and api's. You decide how you
            extend it and choose the best packages from major framework or standalone projects.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/zendframework/zend-diactoros" target="_blank">
                <i class="fa fa-exchange"></i> HTTP Messages
            </a>
        </h2>
        <p>
            HTTP messages are the foundation of web development. Web browsers and HTTP clients such as cURL create
            HTTP request messages that are sent to a web server, which provides an HTTP response message.
            Server-side code receives an HTTP request message, and returns an HTTP response message.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/zendframework/zend-stratigility" target="_blank">
                <i class="fa fa-dot-circle-o"></i> Middleware
            </a>
        </h2>
        <p>
            Middleware is code that exists between the request and response, and which can take the incoming
            request, perform actions based on it, and either complete the response or pass delegation on to the
            next middleware in the queue. Your application is easily extended with custom middleware created by
            yourself or <a href="https://packagist.org/search/?q=middleware" target="_blank">others</a>.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://zend-expressive.readthedocs.org/en/latest/container/intro/" target="_blank">
                <i class="fa fa-cube"></i> Containers
            </a>
        </h2>
        <p>
            Expressive promotes and advocates the usage of Dependency Injection/Inversion of Control containers
            when writing your applications. Expressive supports multiple containers which typehints against
            <a href="https://github.com/container-interop/container-interop" target="_blank">container-interop</a>.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="<?=$this->e($routerDocsUrl)?>" target="_blank">
                <i class="fa fa-plane"></i> <?=$this->e($routerName)?>
            </a>
        </h2>
        <p>
            One fundamental feature of zend-expressive is that it provides mechanisms for implementing dynamic
            routing, a feature required in most modern web applications. Expressive ships with multiple adapters.
            Learn more about <a href="<?=$this->e($routerExtUrl)?>" target="_blank"><?=$this->e($routerName)?></a>.
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://zend-expressive.readthedocs.org/en/latest/template/plates/" target="_blank">
                <i class="fa fa-files-o"></i> Plates Template Engine
            </a>
        </h2>
        <p>
            Plates is a native PHP template system that's fast and easy to use and extend. It strives to bring modern
            template language functionality to native PHP templates. Plates is designed for developers who prefer to
            use native PHP templates over compiled template languages, such as Twig or Smarty.
            Learn more about <a href="http://platesphp.com/" target="_blank">Plates</a>.
        </p>
    </div>
</div>
