name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'
    tags:

env:
  default_php: 8.2

jobs:
  matrix:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Gather CI configuration
        id: matrix
        uses: laminas/laminas-ci-matrix-action@v1

  qa:
    name: QA Checks
    needs: [matrix]
    runs-on: ${{ matrix.operatingSystem }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - name: ${{ matrix.name }}
        uses: laminas/laminas-continuous-integration-action@v1
        with:
          job: ${{ matrix.job }}

  #
  # Runs CS in a separate job because composer plugins need to run here, but must be disabled
  # everywhere else in the matrix.
  #
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: shivammathur/setup-php@2.36.0
        with:
          php-version: ${{ env.default_php }}
          tools: composer
      - uses: ramsey/composer-install@3.1.1
        with:
          composer-options: "--no-scripts"
      - run: vendor/bin/phpcs
